uploads = []

[[generated]]
id = "bKFqSa0iFKRvZ88QkEnqU"
uri = "file://public/stickers/vs.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cdpN4TrX3RtgbwhdrDGsu"
uri = "file://public/stickers/scam.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GzvB443Kf0V1koy2AP7Su"
uri = "file://public/stickers/expose.png"
type = "image"
title = "generated_image"

[[generated]]
id = "18CBedfdMIjbHlY5Toh3A"
uri = "file://public/stickers/water.png"
type = "image"
title = "generated_image"

[[generated]]
id = "OeckdE92p2djdilqc0nbu"
uri = "file://public/stickers/demolish.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kAlBF82CTLUzdVSXIzy45"
uri = "file://public/stickers/flood.png"
type = "image"
title = "generated_image"

[[generated]]
id = "huNldl-dJUkpsig8FFzgU"
uri = "file://public/stickers/power.png"
type = "image"
title = "generated_image"

[[generated]]
id = "6efW-j952BK_bJm5NKPhN"
uri = "file://public/stickers/land.png"
type = "image"
title = "generated_image"

[[generated]]
id = "azSh-36xDkVgeJl_OhXfF"
uri = "file://public/stickers/fist.png"
type = "image"
title = "generated_image"

[[generated]]
id = "6Z1Au9VD9JIwdKKuItlAD"
uri = "file://public/stickers/alert.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "UFWH6okMy4FkECoe2Eb7k"
uri = "file://persona-eb-deployment.zip"
type = "unspecified"
title = "persona-eb-deployment.zip — AWS Elastic Beanstalk Package"

[[outputs]]
id = "BiQ5AcQHvIhCaTlhX8z44"
uri = "file://brs-connect-eb-20260315.zip"
type = "unspecified"
title = "BRS Connect - AWS Elastic Beanstalk Deployment ZIP"

[[outputs]]
id = "PT-p93UtJ0Jojwbt5O-Yn"
uri = "file://brs-connect-eb-deploy.zip"
type = "unspecified"
title = "BRS Connect - AWS Elastic Beanstalk Deploy"

[[outputs]]
id = "K2Fy3V791ldwhsHBjsxor"
uri = "file://connect_aws.zip"
type = "unspecified"
title = "connect_aws.zip"

[[outputs]]
id = "gh5egkSJQn-OfZvVLNjac"
uri = "file://AWS_DEPLOYMENT_GUIDE.md"
type = "text"
title = "Complete AWS Deployment Guide — Step by Step"

[[outputs]]
id = "qQJLeBtPZdjVto8cZO4K0"
uri = "file://brs-connect-latest.zip"
type = "unspecified"
title = "brs-connect-latest.zip — AWS EB Deployment Package"

[[outputs]]
id = "OBdhBO5peUTOsg4ziTJgs"
uri = "file://new-aws.zip"
type = "unspecified"
title = "new-aws.zip — AWS Elastic Beanstalk deployment"
